name: Build and Deploy GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy assets to docs folder
        run: |
          echo "Copying assets folder to docs..."
          cp -r assets docs/
          echo "Assets copied successfully"
      - name: List docs contents
        run: |
          echo "Contents of docs folder:"
          ls -la docs/
          echo "Contents of docs/assets:"
          ls -la docs/assets/ || echo "No assets folder"
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
