name: Test GitHub Pages After Deployment

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      deployment_url:
        description: 'GitHub Pages URL to test'
        required: false
        default: 'https://ragedunicorn.github.io/wow-classic-pvpwarn-vpnfc/'

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event.deployment_status.state == 'success' &&
       github.event.deployment.environment == 'github-pages')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Wait for GitHub Pages propagation
        run: |
          echo "Waiting 30 seconds for GitHub Pages to fully propagate..."
          sleep 30

      - name: Debug GitHub Context
        if: github.event_name == 'deployment_status'
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Deployment URL: ${{ github.event.deployment.payload.web_url || 'not found' }}"
          echo "Deployment environment: ${{ github.event.deployment.environment }}"
          echo "Full deployment payload:"
          echo '${{ toJSON(github.event.deployment) }}'
          
      - name: Set GitHub Pages URL
        id: set-url
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "url=${{ github.event.inputs.deployment_url }}" >> $GITHUB_OUTPUT
          else
            # For deployment_status events, use the deployment URL if available
            if [ -n "${{ github.event.deployment.payload.web_url }}" ]; then
              echo "url=${{ github.event.deployment.payload.web_url }}" >> $GITHUB_OUTPUT
            else
              # Fallback: construct from repository name
              REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
              OWNER=$(echo "${{ github.repository }}" | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
              echo "url=https://${OWNER}.github.io/${REPO_NAME}/" >> $GITHUB_OUTPUT
            fi
          fi
      
      - name: Run Playwright tests
        run: |
          echo "Testing GitHub Pages at: ${{ steps.set-url.outputs.url }}"
          npm test
        env:
          GITHUB_PAGES_URL: ${{ steps.set-url.outputs.url }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7
